<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netcoreapp1.1</TargetFramework>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
    <PackageId>JB2.Common.Date</PackageId>
    <Version>0.3.0</Version>
    <Authors>Joshua Bennett</Authors>
    <Company>JBsquared LLC</Company>
    <Product>Common Lib</Product>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\JB2.Common.Core\JB2.Common.Core.csproj" />
  </ItemGroup>

</Project>