<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <VersionPrefix>0.4.5</VersionPrefix>
    <TargetFramework>netstandard1.6</TargetFramework>
    <AssemblyName>Backup</AssemblyName>
    <PackageId>Backup</PackageId>
    <NetStandardImplicitPackageVersion>1.6.0</NetStandardImplicitPackageVersion>
    <PackageTargetFallback>$(PackageTargetFallback);dnxcore50</PackageTargetFallback>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.Threading.Thread" Version="4.0.0" />
  </ItemGroup>

</Project>
