<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netcoreapp1.1</TargetFramework>
    <AssemblyName>JB2.Common.Exceptions</AssemblyName>
    <RootNamespace>JB2.Common</RootNamespace>
    <PackageId>JB2.Common.Exceptions.NetCore11</PackageId>
    <Version>0.1.3</Version>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\JB2.Common.Core\JB2.Common.Core.csproj" />
  </ItemGroup>

</Project>