<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netcoreapp1.1</TargetFramework>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
    <PackageId>JB2.Common.Image.NetCore11</PackageId>
    <Version>0.2.2</Version>
    <Authors>Joshua Allen Bennett</Authors>
    <Company>JBsquared LLC</Company>
    <Product>Common Lib</Product>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CoreCompat.System.Drawing" Version="1.0.0-beta006" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\JB2.Common.Core\JB2.Common.Core.csproj" />
  </ItemGroup>

</Project>