<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <VersionPrefix>0.4.5</VersionPrefix>
    <TargetFramework>netstandard1.6</TargetFramework>
    <AssemblyName>JB2.Common.Core.NetCore</AssemblyName>
    <PackageId>JB2.Common.Core.NetCore</PackageId>
    <NetStandardImplicitPackageVersion>1.6.0</NetStandardImplicitPackageVersion>
    <PackageTargetFallback>$(PackageTargetFallback);dnxcore50</PackageTargetFallback>
    <GenerateAssemblyConfigurationAttribute>false</GenerateAssemblyConfigurationAttribute>
    <GenerateAssemblyCompanyAttribute>false</GenerateAssemblyCompanyAttribute>
    <GenerateAssemblyProductAttribute>false</GenerateAssemblyProductAttribute>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.Threading.Thread" Version="4.0.0" />
  </ItemGroup>

</Project>
