<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netcoreapp1.1</TargetFramework>
    <Version>0.1.2</Version>
    <PackageId>JB2.Common.Scheduler.NetCore11</PackageId>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
    <Authors>Joshua Bennett</Authors>
    <Company>JBsquared LLC</Company>
    <Product>JBsquared Common Lib</Product>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\JB2.Common.Core\JB2.Common.Core.csproj" />
    <ProjectReference Include="..\JB2.Common.Exceptions\JB2.Common.Exceptions.csproj" />
    <ProjectReference Include="..\JB2.Common.Log\JB2.Common.Log.csproj" />
  </ItemGroup>

</Project>