<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netcoreapp1.1</TargetFramework>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
    <PackageId>JB2.Common.Web.NetCore11</PackageId>
    <Version>0.1.1</Version>
    <Authors>Joshua Allen Bennett</Authors>
    <Company>JBsquared LLC</Company>
    <Product>Common Lib</Product>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="ControllerExtention.cs" />
    <Compile Remove="ImageResult.cs" />
    <Compile Remove="Singleton.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="9.0.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\JB2.Common.Core\JB2.Common.Core.csproj" />
    <ProjectReference Include="..\JB2.Common.Exceptions\JB2.Common.Exceptions.csproj" />
    <ProjectReference Include="..\JB2.Common.Serialization.Json\JB2.Common.Serialization.Json.csproj" />
  </ItemGroup>

</Project>